server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zdzhong/zdzhong-config
          searchPaths: config
      #          username:
      #          password:
      label: master